version: "3.8"

services:
  dns-server:
    build: ./dns
    container_name: dns-server
    ports:
      - "192.168.0.151:53:53/udp"
      - "192.168.0.151:53:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      tracevia-net:
        ipv4_address: 172.25.0.53

  front:
    dns:
      - 172.25.0.53
    build:
      context: ./ligador-wifi
      dockerfile: Dockerfile
    image: wifi-frontend
    restart: always
    ports:
      - "4205:4205"
    environment:
      FRONT_ENV: teste
    networks:
      - tracevia-net

  wifi-mysql:
    image: mysql:8.0
    container_name: wifi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: tracevia_app
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: trcvbr18
    ports:
      - "192.168.0.151:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tracevia-net

  wifi-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wifi-sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "TrcvBr18!"
      TZ: America/Sao_Paulo
    ports:
      - "192.168.0.151:1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - tracevia-net

  nginx:
    dns:
      - 172.25.0.53
    build: ./nginx
    image: wifi-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - asterisk
    volumes:
      - ./certificates/homologacaotracevia.com.br/:/etc/nginx/certs/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/var/www/app-static:ro
    restart: always
    networks:
      - tracevia-net

  asterisk:
#    dns:
#      - 172.25.0.53
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    image: docker-asterisk
    container_name: asterisk
    network_mode: host
    volumes:
      - ./asterisk/config/:/etc/asterisk/:rw
      - ./asterisk/odbc/odbc.ini:/etc/odbc.ini:ro
      - ./asterisk/odbc/odbcinst.ini:/etc/odbcinst.ini:ro
      - ./certificates/homologacaotracevia.com.br/:/etc/asterisk/keys/:ro
      - asterisk-data:/var/lib/asterisk
      - asterisk-logs:/var/log/asterisk
      - asterisk-spool:/var/spool/asterisk
    environment:
      TZ: America/Sao_Paulo
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "asterisk -rx 'core show uptime' >/dev/null 2>&1"]
      interval: 20s
      timeout: 5s
      retries: 5

  coturn:
    image: instrumentisto/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf", "-v"]

networks:
  tracevia-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  asterisk-data:
  asterisk-logs:
  asterisk-spool:
  mysql-data:
  sqlserver-data:
