listening-port=3478
listening-ip=192.168.2.151
relay-ip=192.168.2.151

realm=homologacaotracevia.com.br
server-name=homologacaotracevia.com.br

fingerprint
use-auth-secret
static-auth-secret=1234
stale-nonce=600

total-quota=0
bps-capacity=0

min-port=49160
max-port=49200

log-file=/var/log/turn.log
simple-log
no-multicast-peers
no-cli
