listening-port=3478

fingerprint
lt-cred-mech

realm=homologacaotracevia.com.br
server-name=turn.homologacaotracevia.com.br

user=tracevia:1234

listening-ip=192.168.2.151
relay-ip=192.168.2.151

min-port=49160
max-port=49200

# Desliga interfaces/recursos que estão gerando ruído
no-cli
no-tls
no-dtls

verbose

