[MariaDB ODBC 3.1 Driver]
Description=MariaDB ODBC Driver
Driver=/usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
UsageCount=1

; ==========================
; SQL Server ODBC Driver
; (requer msodbcsql18 + unixODBC instalados no container/host)
; ==========================
[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.6.so.1.1
UsageCount=1
