;[asterisk-rt]
;Description = MySQL Tracevia
;Driver = MariaDB ODBC 3.1 Driver
;Server = 192.168.0.151
;Port = 3306
;Database = tracevia_app
;UID = backend_user
;PWD = trcvbr18
;Option = 3

; ==========================
; SQL Server Tracevia (RealTime)
; ==========================
[asterisk-rt-mssql]
Description = SQL Server Tracevia
Driver = ODBC Driver 18 for SQL Server
Server = 192.168.0.151
Port = 1433
Database = tracevia_app
UID = sa
PWD = TrcvBr18!
Encrypt = no
TrustServerCertificate = yes
