; ==========================
; Conexão MySQL/MariaDB (ATUAL)
; ==========================
;[asterisk-rt]
;enabled=yes
;dsn=asterisk-rt
;username=backend_user
;password=trcvbr18
;pre-connect=yes

; Conexão para RealTime (pjsip) - ATUAL
[asterisk]
enable=no
;enabled=yes
;dsn=asterisk-rt
;username=backend_user
;password=trcvbr18
;pre-connect=yes

; ==========================
; Conexão SQL Server (FUTURA)
; ==========================
[asterisk-mssql]
enabled=yes
dsn=asterisk-rt-mssql
username=sa
password=TrcvBr18!
pre-connect=yes
